# Generated by Django 3.1.7 on 2021-02-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatapp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatapp',
            name='username',
        ),
    ]
