# Generated by Django 3.1.7 on 2021-02-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_chatapp_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatapp',
            name='room',
        ),
    ]
