# Generated by Django 3.1.7 on 2021-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_remove_chatapp_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatapp',
            name='room',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
