# Generated by Django 3.1.7 on 2021-03-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0014_chatapp_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatapp',
            name='room',
        ),
    ]
