# Generated by Django 3.1.7 on 2021-03-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0016_chatapp_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatapp',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatapp.room'),
            preserve_default=False,
        ),
    ]
